### ISSUE TITLE
Advantages over using the official XBox app via sideload?

### ISSUE THREAD

**Issue by GitPugged** [mistertest/xcloud-shield#35]
Hello,

since the latest version number (4.4) dates back to november of last year, I'm curious whether this app currently still provides any performance increase vs. using the official app from Microsoft.  The Xbox Game Pass app seems to have issues with 4K displays, as the stream quality is significantly worse than in FullHD.

I'm using a Nvidia Shield TV Pro and even that device doesn't seem to be able to properly apply the AI upscaling to the stream, so it often feels like a pixelated mess. I'm wondering whether your app would improve on that.

Kind regards

**Comment by mistertest** [comment]
Hello, for a 4K setup or a upscaling, this custom app is not a good choice. Because the technology behind the app, "Webview" is not compatible with upscaling. But you'll have to know that when you run a thing with upscaling on the shield, you 'll not have 60 fps. But with a 1080 p/60fps, my app is a good choice, and like many users explain that : the app is more smooth and have a better rendrering than the official app in this conditions.

**Comment by GitPugged** [comment]
It's a shame that XCloud hasn't embraced UHD yet, it's what's holding me back from being a permanent Ultimate subscriber. If a service like Stadia can offer a 4K stream, you would think Microsoft can do so as well.

Anyway, thanks for the heads-up. I might have to look at alternatives then, since all my displays are 4K at this point.
